# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='subject',
            new_name='name',
        ),
    ]
