# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0002_auto_20170619_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('experience', models.TextField(max_length=11000)),
            ],
        ),
    ]
