# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functions', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=9000),
        ),
    ]
